# Generated by Django 5.2.6 on 2025-10-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_borrowrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateField(blank=True, null=True, verbose_name='借閱日期'),
        ),
    ]
